networks:
  # The presence of these objects is sufficient to define them
  expense: {}

volumes:
 mysql:

services:
  mysql:
    image: mysql:1.0.0
    networks:
      - expense
    container_name: mysql
    volumes:
      - db-data:/var/lib/mysql
  
  backend:
    image: backend:1.0.0
    networks:
      - expense
    container_name: backend
    depends_on:
     - mysql

  backend:
    image: frontend:1.0.0
    networks:
      - expense
    container_name: frontend
    ports:
     - 80:80
    depends_on:
     - backend
 



