networks:
  # The presence of these objects is sufficient to define them
  expense: {}

volumes:
 mysql:

services:
  mysql:
    image: manjudbadevops/mysql:1.0.0
    networks:
      - expense
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql
  
  backend:
    image: manjudbadevops/backend:1.0.0
    command: sh -c "sleep 5 && node /app/index.js"
    networks:
      - expense
    container_name: backend
    depends_on:
     - mysql

  frontend:
    image: manjudbadevops/frontend:1.0.0
    networks:
      - expense
    container_name: frontend
    ports:
     - 80:80
    depends_on:
     - backend
 



